name: build

on: [push]

jobs:
  win:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: |
        choco install vulkan-sdk
        refreshenv
        echo VULKAN_SDK
        echo VK_SDK_PATH
    - name: build
      run: |
        cmake --version
        cmake -B build -DCMAKE_BUILD_TYPE=Debug
        cmake --build build
        
